import React from 'react';
import { FileText } from 'lucide-react';

const sections = [
  {
    title: 'Using MapMingle',
    body: 'MapMingle provides an AI-powered travel discovery platform. By creating an account or using any feature of the service, you agree to these terms. You must be at least 13 years old to use MapMingle.',
  },
  {
    title: 'AI-generated content',
    body: 'Travel recommendations, itineraries, and location data generated by our AI are provided for informational purposes only. Always verify critical information — opening hours, entry fees, safety conditions — locally or through official sources. MapMingle is not liable for inaccuracies in AI-generated content.',
  },
  {
    title: 'User content',
    body: 'You retain ownership of content you post on MapMingle (photos, captions, reviews). By posting, you grant MapMingle a non-exclusive licence to display and distribute that content within the platform. You are responsible for ensuring your content does not violate any laws or third-party rights.',
  },
  {
    title: 'Prohibited behaviour',
    body: 'You agree not to post harmful, misleading, or illegal content; impersonate other users or guides; use the platform for spam or unsolicited commercial messages; or attempt to access other users\' accounts or private data.',
  },
  {
    title: 'Guide bookings',
    body: 'Tour packages and bookings facilitated through MapMingle are agreements between travellers and local guides. MapMingle acts as a platform and is not a party to these agreements. We recommend verifying guide credentials and agreeing on terms before any booking.',
  },
  {
    title: 'Limitation of liability',
    body: 'MapMingle is provided "as is" without warranties of any kind. To the maximum extent permitted by law, MapMingle shall not be liable for any indirect, incidental, or consequential damages arising from use of the platform.',
  },
  {
    title: 'Changes to these terms',
    body: 'We may revise these terms at any time. Continued use of MapMingle after changes are posted constitutes your acceptance of the revised terms. We will notify users of material changes via the platform.',
  },
];

const Terms: React.FC = () => {
  return (
    <div className="max-w-2xl mx-auto px-4 sm:px-6 py-16">
      {/* Header */}
      <div className="mb-12">
        <div className="w-10 h-10 bg-gray-100 rounded-xl flex items-center justify-center mb-5 border border-gray-200">
          <FileText size={20} className="text-gray-600" />
        </div>
        <h1 className="text-4xl font-bold text-gray-900 mb-3">Terms of Service</h1>
        <p className="text-gray-400 text-sm">Last updated: April 2025</p>
      </div>

      {/* Intro */}
      <p className="text-gray-500 leading-relaxed mb-10">
        These terms govern your use of MapMingle. We've written them to be straightforward.
        If you have questions, feel free to reach out.
      </p>

      {/* Sections */}
      <div className="space-y-8">
        {sections.map(({ title, body }) => (
          <div key={title} className="border-t border-gray-100 pt-8">
            <h2 className="text-base font-bold text-gray-900 mb-2">{title}</h2>
            <p className="text-gray-500 text-sm leading-relaxed">{body}</p>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Terms;
